name: Unit tests

on:
  push:
    branches: [ 'main', 'github-checks']
    # only trigger workflow on changes in the sk_cathode subdirectory
    paths:
        - 'sk_cathode/**'
  pull_request:
    branches: [ '*' ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    container:
      image: jobirk/sk_cathode:latest
    steps:
      - uses: actions/checkout@v3
      - name: Test with pytest
        run: pytest
